icaas: Parse input options with getopts
Expect to find the manifest as the first argument and add -l option that
allows the user to define a logfile.

diff --git a/bin/icaas b/bin/icaas
--- a/bin/icaas
+++ b/bin/icaas
@@ -17,27 +17,71 @@
 
 set -e
 
-# Redirect everything to icass.log
-exec >/var/log/icaas.log 2>&1
+
+usage() {
+    local rc="$1"
+
+    cat <<EOF
+
+Usage: $0 [options] <manifest>
+
+Create an image and register it with a synnefo deployment according to the
+specifications found in the manifest file.
+
+OPTIONS:
+    -l LOGFILE
+        Log the output to this file
+
+    -h Print this message
+
+EOF
+
+    exit "$rc"
+}
 
 error() { echo "$(date) [ERROR] $@" >&2; exit 1; }
 warn() { echo "$(date) [WARNING] $@" >&2; }
 info() { echo "$(date) [INFO] $@" >&2; }
 
-info "Starting Image Creator as a Service"
 
-if [ -f /var/lib/icaas/manifest.sh ]; then
-    source /var/lib/icaas/manifest.sh
-else
-    error "Manifest file: \`/var/lib/icaas/manifest.sh' not found"
+while getopts "l:h" opt; do
+    case $opt in
+        l) LOGFILE="$OPTARG"
+            ;;
+        h) usage 0
+            ;;
+        ?) usage 1
+            ;;
+    esac
+done
+
+shift $((OPTIND-1))
+
+if [ -z "$1" ]; then
+    echo -e "Manifest missing." >&2
+    usage 2
 fi
 
+MANIFEST="$1"
+
+if [ -f "$MANIFEST" ]; then
+    source "$MANIFEST"
+else
+   echo "Manifest file: \`$MANIFEST' does not exist. Type $0 -h for help"
+   exit 3
+fi
+
+if [ "$LOGFILE" != "" ]; then
+    # Redirect everything the $LOGFILE
+    exec >$LOGFILE 2>&1
+fi
+
+info "Starting Image Creator as a Service"
 
 FILENAME=$(basename "$ICAAS_IMAGE_URL")
 BASENAME=$(basename "$ICAAS_IMAGE_URL" .zip)
 if [[ ! "$FILENAME" =~ ^bitnami-[A-Za-z0-9.-]+\.zip ]]; then
-    error "$FILENAME"
-    #error "$ICAAS_IMAGE_URL donsn't look like a bitnami image"
+    error "$FILENAME is not a bitnami image"
 fi
 
 CONTAINER=${ICAAS_IMAGE_OBJECT%/*}
@@ -47,18 +91,19 @@ info "Downloading image from: $ICAAS_IMAGE_URL"
 curl -L "$ICAAS_IMAGE_URL" > "/var/tmp/$FILENAME"
 
 info "Unpacking zip file"
-(
-    cd /var/tmp;
-    rm -rf /var/tmp/$BASENAME;
-    unzip -o -f /var/tmp/$FILENAME;
-    rm -f "!$";
-)
+cd /var/tmp;
+rm -rf /var/tmp/$BASENAME;
+unzip -o -u /var/tmp/$FILENAME;
+rm -f "!$";
+cd -
 
 IMAGE=/var/tmp/$BASENAME/$BASENAME.vmdk
 
 info "Creating image with snf-image-creator"
 snf-mkimage -u "$OBJECT" -a "$ICAAS_SERVICE_URL" -t "$ICAAS_SERVICE_TOKEN" \
     -r "$ICAAS_IMAGE_NAME" -m DESCRIPTION="$ICAAS_IMAGE_DESCRIPTION" "$IMAGE"
+
+info "Image Creator as a Service finished"
 
 # vim: set sta sts=4 shiftwidth=4 sw=4 et ai :
 
